// Generates the Cloudflare Worker source (a self-contained ES module) that acts
// as the ONLY public gateway for the APiX TV app.
//
// The generated Worker:
//   1. Proxies /rest/v1/* and /functions/v1/* to Supabase using HIDDEN secrets
//      (SUPA_URL, SUPA_ANON) injected as Worker secret_text bindings — never in
//      plaintext source.
//   2. AES-256-GCM encrypts JSON bodies returned from the database tables using
//      the injected ENC_KEY (32-byte hex/base64, raw key — matches the Android
//      C++/JNI decryptor and the cached-data edge function format { iv, data }).
//   3. Edge ban system: pulls the banned device-id / IP list once and keeps it in
//      memory; rejects banned fingerprints with 403 WITHOUT hitting Supabase.
//   4. APK CDN: caches /apk/* and update binaries on the edge to save bandwidth.
//
// NOTE: the returned string is plain JavaScript so it runs on the Cloudflare
// runtime without a build step.

export function buildWorkerScript(): string {
  return String.raw`
// ===== APiX TV Edge Gateway (auto-generated by the panel — do not edit) =====
// Secrets are injected as Worker bindings: SUPA_URL, SUPA_ANON, ENC_KEY,
// optional BAN_ENDPOINT, optional ALLOWED_ORIGINS.

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, if-none-match, x-device-id, x-app-version",
  "Access-Control-Allow-Methods": "GET, POST, PUT, PATCH, DELETE, OPTIONS",
  "Access-Control-Expose-Headers": "etag, x-cache, x-payload-encryption",
};

// ---- AES-256-GCM helpers (raw 32-byte key, no hashing) ----
function decodeKey(raw) {
  const t = (raw || "").trim();
  if (!t) throw new Error("ENC_KEY not set");
  if (/^[0-9a-fA-F]{64}$/.test(t)) {
    const out = new Uint8Array(32);
    for (let i = 0; i < 32; i++) out[i] = parseInt(t.substr(i * 2, 2), 16);
    return out;
  }
  const bin = atob(t.replace(/-/g, "+").replace(/_/g, "/"));
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  if (out.length !== 32) throw new Error("ENC_KEY must decode to 32 bytes");
  return out;
}
function b64(bytes) {
  let s = "";
  for (let i = 0; i < bytes.byteLength; i++) s += String.fromCharCode(bytes[i]);
  return btoa(s);
}
let _key = null;
async function getKey(env) {
  if (_key) return _key;
  _key = await crypto.subtle.importKey("raw", decodeKey(env.ENC_KEY),
    { name: "AES-GCM" }, false, ["encrypt"]);
  return _key;
}
async function encryptJson(env, plain) {
  const key = await getKey(env);
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ct = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key,
    new TextEncoder().encode(plain));
  return JSON.stringify({ iv: b64(iv), data: b64(new Uint8Array(ct)) });
}

// ---- Edge ban cache ----
let _bans = { ids: new Set(), ips: new Set(), at: 0 };
const BAN_TTL_MS = 5 * 60 * 1000;
async function refreshBans(env) {
  if (Date.now() - _bans.at < BAN_TTL_MS) return;
  try {
    const url = env.BAN_ENDPOINT ||
      (env.SUPA_URL + "/functions/v1/admin-ban?action=list");
    const r = await fetch(url, {
      headers: { apikey: env.SUPA_ANON, Authorization: "Bearer " + env.SUPA_ANON },
    });
    if (r.ok) {
      const j = await r.json().catch(() => null);
      const ids = new Set(), ips = new Set();
      const rows = Array.isArray(j) ? j : (j && j.banned) || [];
      for (const b of rows) {
        if (b && b.device_id) ids.add(String(b.device_id));
        if (b && b.ip_address) ips.add(String(b.ip_address));
      }
      _bans = { ids, ips, at: Date.now() };
    } else {
      _bans.at = Date.now(); // avoid hammering on failure
    }
  } catch (_) {
    _bans.at = Date.now();
  }
}
function isBanned(deviceId, ip) {
  if (deviceId && _bans.ids.has(deviceId)) return true;
  if (ip && _bans.ips.has(ip)) return true;
  return false;
}

const ENCRYPT_PATHS = ["/rest/v1/categories", "/rest/v1/channels",
  "/rest/v1/side_menus", "/rest/v1/sub_channels", "/rest/v1/custom_ads",
  "/rest/v1/system_settings", "/functions/v1/cached-data"];

export default {
  async fetch(request, env, ctx) {
    if (request.method === "OPTIONS") return new Response(null, { headers: CORS });
    const url = new URL(request.url);
    const deviceId = request.headers.get("x-device-id") || "";
    const ip = request.headers.get("cf-connecting-ip") ||
      request.headers.get("x-forwarded-for") || "";

    // 1) Edge ban — reject before touching Supabase
    await refreshBans(env);
    if (isBanned(deviceId, ip)) {
      return new Response(JSON.stringify({ error: "forbidden", banned: true }),
        { status: 403, headers: { ...CORS, "Content-Type": "application/json" } });
    }

    // 2) APK / update CDN — cache on the edge to save Supabase bandwidth
    if (url.pathname.startsWith("/apk/") || url.pathname.startsWith("/cdn/")) {
      const cache = caches.default;
      let res = await cache.match(request);
      if (res) return res;
      const target = env.SUPA_URL + "/storage/v1/object/public/app-builds/" +
        url.pathname.replace(/^\/(apk|cdn)\//, "");
      res = await fetch(target);
      res = new Response(res.body, res);
      res.headers.set("Cache-Control", "public, max-age=86400");
      res.headers.set("X-Cache", "EDGE");
      ctx.waitUntil(cache.put(request, res.clone()));
      return res;
    }

    // 3) Proxy /rest/v1/* and /functions/v1/* to Supabase with hidden keys
    if (url.pathname.startsWith("/rest/v1/") || url.pathname.startsWith("/functions/v1/")) {
      const target = env.SUPA_URL + url.pathname + url.search;
      const headers = new Headers(request.headers);
      headers.set("apikey", env.SUPA_ANON);
      headers.set("Authorization", "Bearer " + env.SUPA_ANON);
      headers.delete("host");
      const init = { method: request.method, headers };
      if (request.method !== "GET" && request.method !== "HEAD") {
        init.body = await request.arrayBuffer();
      }
      const upstream = await fetch(target, init);

      const shouldEncrypt = request.method === "GET" &&
        ENCRYPT_PATHS.some((p) => url.pathname.startsWith(p)) &&
        upstream.headers.get("x-payload-encryption") == null;

      if (shouldEncrypt && upstream.ok) {
        const text = await upstream.text();
        let body;
        try { body = await encryptJson(env, text); }
        catch (_) { body = text; }
        return new Response(body, {
          status: upstream.status,
          headers: { ...CORS, "Content-Type": "application/json",
            "X-Payload-Encryption": "AES-256-GCM" },
        });
      }
      const out = new Response(upstream.body, upstream);
      for (const [k, v] of Object.entries(CORS)) out.headers.set(k, v);
      return out;
    }

    if (url.pathname === "/" || url.pathname === "/health") {
      return new Response(JSON.stringify({ ok: true, gateway: "apix-edge" }),
        { headers: { ...CORS, "Content-Type": "application/json" } });
    }
    return new Response("Not found", { status: 404, headers: CORS });
  },
};
`;
}
