# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.mpp.applyDefaultHierarchyTemplate=false

# Bypass AGP 9.0 built-in Kotlin to support KAPT for Room Database
android.builtInKotlin=false
android.newDsl=false
