pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://jitpack.io") }
    }
}

rootProject.name = "APiX"

include ':app'
include ':movies-library'
include ':movies'

project(':movies-library').projectDir = file('app/src/main/java/com/apix/app/ui/Home/Movies/Move/CoreLibrary/src')
project(':movies').projectDir = file('app/src/main/java/com/apix/app/ui/Home/Movies/Move/MovieEngine')
