name: APiXTV
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: '16.0'
    TARGETED_DEVICE_FAMILY: '1,2'
    PRODUCT_BUNDLE_IDENTIFIER: com.apix.app.ios
    PRODUCT_NAME: APiXTV
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Manual
    DEVELOPMENT_TEAM: ''
    GENERATE_INFOPLIST_FILE: NO
    INFOPLIST_KEY_UISupportedInterfaceOrientations: 'UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight'
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: 'UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight'
packages: {}
targets:
  APiXTV:
    type: application
    platform: iOS
    deploymentTarget: '16.0'
    sources:
      - path: APiXTV
    settings:
      base:
        INFOPLIST_FILE: APiXTV/Info.plist
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ''
        SUPPORTS_MACCATALYST: NO
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
