ALTER TABLE public.channels
  ADD COLUMN IF NOT EXISTS hidden_android BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS hidden_ios BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS hidden_windows BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS hidden_web BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE public.sub_channels
  ADD COLUMN IF NOT EXISTS hidden_android BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS hidden_ios BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS hidden_windows BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS hidden_web BOOLEAN NOT NULL DEFAULT false;