@JvmStatic fun ka(): String = a()
    @JvmStatic fun kb(): String = b()
    @JvmStatic fun kc(): String = c()
    @JvmStatic fun kd(): String = d()
    @JvmStatic fun ke(): String = e()
    @JvmStatic fun kf(): String = f()
    @JvmStatic fun kg(): String = g()